workspace 'AlxAdsDemo'
platform :ios, '13.0'
use_frameworks!

# Demo工程
project 'AlxAdsDemo.xcodeproj'
target 'AlxAdsDemo' do
  project 'AlxAdsDemo.xcodeproj'
  
  # 添加SDK依赖库
  # RixEngineAds
  pod 'RixEngineAds/AdmobAdapter', '2.0.2'
  pod 'RixEngineAds/MaxAdapter', '2.0.2'
  pod 'RixEngineAds/TopOnAdapter', '2.0.2'
  pod 'RixEngineAds/UnityLevelPlayAdapter', '2.0.2'
end


