workspace 'AlxAdsDemo'
platform :ios, '13.0'
use_frameworks!

# Demo工程
project 'AlxAdsDemo.xcodeproj'
target 'AlxAdsDemo' do
  project 'AlxAdsDemo.xcodeproj'
  
  # 添加SDK依赖库
  # RixEngineAds
  pod 'RixEngineAds/AdmobAdapter'
  pod 'RixEngineAds/MaxAdapter'
  pod 'RixEngineAds/TopOnAdapter'
  pod 'RixEngineAds/UnityLevelPlayAdapter'
end


